import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)

COMPOUNDS = [
  # ── SODIUM (Z=11) ──────────────────────────────────────────
  {
    "formula": "NaCl",
    "name_common": "Sodium chloride",
    "name_iupac": "Sodium chloride",
    "cas_number": "7647-14-5",
    "primary_element_atomic_number": 11,
    "primary_element_symbol": "Na",
    "oxidation_state_of_element": 1,
    "compound_class": "halide",
    "molecular_mass": 58.44,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White cubic crystals",
    "odor": "Odorless",
    "melting_point": 1074.0,
    "boiling_point": 1738.0,
    "density": 2.165,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice",
    "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic",
    "bond_angle": "90° (cubic lattice)",
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": 6,
    "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. pH of solution ≈ 7.",
    "std_enthalpy_formation": -411.2,
    "std_gibbs_free_energy": -384.1,
    "std_entropy": 72.1,
    "lattice_energy": -787.0,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 3000.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Generally safe. Excessive use can salinize soil and water bodies.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Food seasoning, food preservation, de-icing roads, chlorine and NaOH production (chloralkali process).",
    "industrial_production_method": "Mining of halite deposits or solar evaporation of seawater.",
    "notes": "NaCl-type crystal structure. Coordination number 6:6. Each Na+ surrounded by 6 Cl- and vice versa.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "NaOH",
    "name_common": "Sodium hydroxide",
    "name_iupac": "Sodium hydroxide",
    "cas_number": "1310-73-2",
    "primary_element_atomic_number": 11,
    "primary_element_symbol": "Na",
    "oxidation_state_of_element": 1,
    "compound_class": "hydroxide",
    "molecular_mass": 40.00,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White waxy solid, pellets or flakes",
    "odor": "Odorless",
    "melting_point": 596.0,
    "boiling_point": 1661.0,
    "density": 2.13,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic",
    "electron_pair_geometry": "ionic",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Strong base. Fully dissociates in water. pH of 0.1M solution ≈ 13.",
    "std_enthalpy_formation": -425.9,
    "std_gibbs_free_energy": -379.5,
    "std_entropy": 64.4,
    "lattice_energy": None,
    "ghs_hazard_codes": "H290, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": 325.0,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Raises pH of water bodies. Harmful to aquatic life at high concentrations.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": 1807,
    "uses": "Soap making, paper industry, drain cleaners, aluminium production, food processing (pretzel browning).",
    "industrial_production_method": "Chloralkali process: 2NaCl + 2H2O → Cl2 + H2 + 2NaOH",
    "notes": "Also called caustic soda or lye. Highly exothermic dissolution in water. Absorbs CO2 from air.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Na2O",
    "name_common": "Sodium oxide",
    "name_iupac": "Disodium oxide",
    "cas_number": "1313-59-3",
    "primary_element_atomic_number": 11,
    "primary_element_symbol": "Na",
    "oxidation_state_of_element": 1,
    "compound_class": "oxide",
    "molecular_mass": 61.98,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White crystalline solid",
    "odor": "Odorless",
    "melting_point": 1548.0,
    "boiling_point": None,
    "density": 2.27,
    "solubility_in_water": "reacts",
    "molecular_geometry": "ionic lattice",
    "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Reacts vigorously with water: Na2O + H2O → 2NaOH",
    "std_enthalpy_formation": -414.2,
    "std_gibbs_free_energy": -375.5,
    "std_entropy": 75.1,
    "lattice_energy": -2909.0,
    "ghs_hazard_codes": "H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Reacts with water to form corrosive NaOH.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Glass manufacturing, chemical synthesis.",
    "industrial_production_method": "4Na + O2 → 2Na2O (limited oxygen conditions)",
    "notes": "Less stable than Na2O2. Reacts with excess oxygen to form Na2O2.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Na2CO3",
    "name_common": "Sodium carbonate",
    "name_iupac": "Disodium carbonate",
    "cas_number": "497-19-8",
    "primary_element_atomic_number": 11,
    "primary_element_symbol": "Na",
    "oxidation_state_of_element": 1,
    "compound_class": "salt",
    "molecular_mass": 105.99,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White powder or granules",
    "odor": "Odorless",
    "melting_point": 1124.0,
    "boiling_point": None,
    "density": 2.54,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic",
    "electron_pair_geometry": "ionic",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic salt. Hydrolyzes to give alkaline solution. pH ≈ 11.6 for 0.1M solution.",
    "std_enthalpy_formation": -1130.7,
    "std_gibbs_free_energy": -1044.4,
    "std_entropy": 134.98,
    "lattice_energy": None,
    "ghs_hazard_codes": "H319",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 4090.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Mildly alkaline. Can affect aquatic pH at high concentrations.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Glass making, paper industry, water softening, detergents. Known as washing soda.",
    "industrial_production_method": "Solvay process: NaCl + CaCO3 → Na2CO3 + CaCl2",
    "notes": "Na2CO3·10H2O is washing soda. Na2CO3·H2O is soda ash.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "NaHCO3",
    "name_common": "Sodium bicarbonate",
    "name_iupac": "Sodium hydrogen carbonate",
    "cas_number": "144-55-8",
    "primary_element_atomic_number": 11,
    "primary_element_symbol": "Na",
    "oxidation_state_of_element": 1,
    "compound_class": "salt",
    "molecular_mass": 84.01,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White crystalline powder",
    "odor": "Odorless",
    "melting_point": None,
    "boiling_point": None,
    "density": 2.20,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic",
    "electron_pair_geometry": "ionic",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Weakly basic salt. pH of 0.1M solution ≈ 8.3. Mild alkali.",
    "std_enthalpy_formation": -950.8,
    "std_gibbs_free_energy": -851.0,
    "std_entropy": 101.7,
    "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 4220.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Generally safe and environmentally benign.",
    "biodegradable": True,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Baking soda, antacid, fire extinguishers, CO2 source in baking.",
    "industrial_production_method": "Na2CO3 + CO2 + H2O → 2NaHCO3",
    "notes": "Decomposes on heating: 2NaHCO3 → Na2CO3 + H2O + CO2 above 50°C.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── MAGNESIUM (Z=12) ────────────────────────────────────────
  {
    "formula": "MgO",
    "name_common": "Magnesium oxide",
    "name_iupac": "Magnesium oxide",
    "cas_number": "1309-48-4",
    "primary_element_atomic_number": 12,
    "primary_element_symbol": "Mg",
    "oxidation_state_of_element": 2,
    "compound_class": "oxide",
    "molecular_mass": 40.30,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White powder",
    "odor": "Odorless",
    "melting_point": 3125.0,
    "boiling_point": 3873.0,
    "density": 3.58,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic lattice",
    "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": 6,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Reacts slowly with water to form Mg(OH)2.",
    "std_enthalpy_formation": -601.6,
    "std_gibbs_free_energy": -569.3,
    "std_entropy": 27.0,
    "lattice_energy": -3795.0,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Environmentally benign. Naturally occurring mineral.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Refractory material, antacid, laxative, crucible lining, supplements.",
    "industrial_production_method": "Calcination of magnesite: MgCO3 → MgO + CO2",
    "notes": "Very high melting point (2852°C). NaCl-type crystal structure. CN = 6:6.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Mg(OH)2",
    "name_common": "Magnesium hydroxide",
    "name_iupac": "Magnesium dihydroxide",
    "cas_number": "1309-42-8",
    "primary_element_atomic_number": 12,
    "primary_element_symbol": "Mg",
    "oxidation_state_of_element": 2,
    "compound_class": "hydroxide",
    "molecular_mass": 58.32,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White amorphous powder",
    "odor": "Odorless",
    "melting_point": 623.0,
    "boiling_point": None,
    "density": 2.34,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic",
    "electron_pair_geometry": "ionic",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Weak base. Ksp = 5.61×10⁻¹². Milk of magnesia.",
    "std_enthalpy_formation": -924.5,
    "std_gibbs_free_energy": -833.5,
    "std_entropy": 63.2,
    "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 8500.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Safe. Used in environmental remediation to neutralize acid spills.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Antacid (milk of magnesia), laxative, flame retardant, wastewater treatment.",
    "industrial_production_method": "MgO + H2O → Mg(OH)2 or precipitation from seawater.",
    "notes": "Decomposes on heating at ~350°C: Mg(OH)2 → MgO + H2O",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "MgCl2",
    "name_common": "Magnesium chloride",
    "name_iupac": "Magnesium dichloride",
    "cas_number": "7786-30-3",
    "primary_element_atomic_number": 12,
    "primary_element_symbol": "Mg",
    "oxidation_state_of_element": 2,
    "compound_class": "halide",
    "molecular_mass": 95.21,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White crystalline solid",
    "odor": "Odorless",
    "melting_point": 987.0,
    "boiling_point": 1685.0,
    "density": 2.32,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice",
    "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": 6,
    "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral to slightly acidic. Mg2+ undergoes slight hydrolysis.",
    "std_enthalpy_formation": -641.3,
    "std_gibbs_free_energy": -591.8,
    "std_entropy": 89.6,
    "lattice_energy": -2526.0,
    "ghs_hazard_codes": "H302",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 2800.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Low toxicity. Can affect freshwater organisms at high concentrations.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "De-icing, dust control, magnesium metal production, tofu coagulant, supplements.",
    "industrial_production_method": "Mg + Cl2 → MgCl2 or from seawater/brine.",
    "notes": "Hygroscopic. CdCl2-type layer structure. Used in Dow process for Mg extraction.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── ALUMINIUM (Z=13) ────────────────────────────────────────
  {
    "formula": "Al2O3",
    "name_common": "Aluminium oxide",
    "name_iupac": "Dialuminium trioxide",
    "cas_number": "1344-28-1",
    "primary_element_atomic_number": 13,
    "primary_element_symbol": "Al",
    "oxidation_state_of_element": 3,
    "compound_class": "oxide",
    "molecular_mass": 101.96,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White powder or colorless crystals (corundum)",
    "odor": "Odorless",
    "melting_point": 2345.0,
    "boiling_point": 3250.0,
    "density": 3.987,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice",
    "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": 6,
    "ligands": None,
    "is_acid": True, "is_base": True, "is_amphoteric": True,
    "acid_base_notes": "Amphoteric. With acid: Al2O3 + 6HCl → 2AlCl3 + 3H2O. With base: Al2O3 + 2NaOH + 3H2O → 2Na[Al(OH)4].",
    "std_enthalpy_formation": -1675.7,
    "std_gibbs_free_energy": -1582.3,
    "std_entropy": 50.9,
    "lattice_energy": -15916.0,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Inert and naturally occurring. Environmentally safe.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Abrasive (corundum, emery), refractory, Al production (Hall-Héroult), gemstones (ruby=Cr-doped, sapphire=Ti-doped).",
    "industrial_production_method": "Bayer process from bauxite: Al(OH)3 → Al2O3 + H2O",
    "notes": "Classic example of amphoteric oxide. α-Al2O3 is corundum (hardness 9 Mohs).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Al(OH)3",
    "name_common": "Aluminium hydroxide",
    "name_iupac": "Aluminium trihydroxide",
    "cas_number": "21645-51-2",
    "primary_element_atomic_number": 13,
    "primary_element_symbol": "Al",
    "oxidation_state_of_element": 3,
    "compound_class": "hydroxide",
    "molecular_mass": 78.00,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White amorphous or crystalline powder",
    "odor": "Odorless",
    "melting_point": None,
    "boiling_point": None,
    "density": 2.42,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic",
    "electron_pair_geometry": "ionic",
    "hybridization": "ionic",
    "bond_angle": None,
    "vsepr_notation": None,
    "is_polar": None,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": True, "is_amphoteric": True,
    "acid_base_notes": "Classic amphoteric hydroxide. As base: Al(OH)3 + 3HCl → AlCl3 + 3H2O. As acid: Al(OH)3 + NaOH → Na[Al(OH)4].",
    "std_enthalpy_formation": -1276.0,
    "std_gibbs_free_energy": -1138.0,
    "std_entropy": 70.0,
    "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Safe. Used in water purification as coagulant.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Antacid, water purification, flame retardant, precursor to Al2O3.",
    "industrial_production_method": "Bayer process: Al2O3 + NaOH + H2O → NaAl(OH)4 → Al(OH)3",
    "notes": "Ksp = 3×10⁻³⁴. Textbook example of amphoteric hydroxide.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "AlCl3",
    "name_common": "Aluminium chloride",
    "name_iupac": "Aluminium trichloride",
    "cas_number": "7446-70-0",
    "primary_element_atomic_number": 13,
    "primary_element_symbol": "Al",
    "oxidation_state_of_element": 3,
    "compound_class": "halide",
    "molecular_mass": 133.34,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White or pale yellow crystalline solid",
    "odor": "Pungent in moist air (HCl release)",
    "melting_point": 463.0,
    "boiling_point": 453.0,
    "density": 2.48,
    "solubility_in_water": "reacts",
    "molecular_geometry": "trigonal planar (monomer) / octahedral (dimer)",
    "electron_pair_geometry": "trigonal planar",
    "hybridization": "sp2",
    "bond_angle": "120°",
    "vsepr_notation": "AX3",
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strong Lewis acid. Al3+ accepts electron pairs. Hydrolyzes: AlCl3 + 3H2O → Al(OH)3 + 3HCl",
    "std_enthalpy_formation": -704.2,
    "std_gibbs_free_energy": -628.8,
    "std_entropy": 110.7,
    "lattice_energy": -5492.0,
    "ghs_hazard_codes": "H290, H314, H335",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": 3450.0,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Corrosive to aquatic life. Handle with care near water bodies.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Friedel-Crafts catalyst, antiperspirants, water treatment, petroleum cracking.",
    "industrial_production_method": "2Al + 3Cl2 → 2AlCl3",
    "notes": "Exists as Al2Cl6 dimer in vapor phase due to Lewis acid-base interaction. Sublimes at 180°C.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── SILICON (Z=14) ──────────────────────────────────────────
  {
    "formula": "SiO2",
    "name_common": "Silicon dioxide",
    "name_iupac": "Silicon dioxide",
    "cas_number": "7631-86-9",
    "primary_element_atomic_number": 14,
    "primary_element_symbol": "Si",
    "oxidation_state_of_element": 4,
    "compound_class": "oxide",
    "molecular_mass": 60.08,
    "physical_state_298k": "solid",
    "color": "colorless",
    "appearance": "Colorless transparent crystals or white powder",
    "odor": "Odorless",
    "melting_point": 1986.0,
    "boiling_point": 2503.0,
    "density": 2.648,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "tetrahedral (each Si)",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "109.5°",
    "vsepr_notation": "AX4",
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": 4,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Acidic oxide. Reacts with bases: SiO2 + 2NaOH → Na2SiO3 + H2O. Resistant to most acids except HF.",
    "std_enthalpy_formation": -910.9,
    "std_gibbs_free_energy": -856.4,
    "std_entropy": 41.8,
    "lattice_energy": None,
    "ghs_hazard_codes": "H350 (crystalline silica only)",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": False, "is_carcinogenic": True,
    "environmental_impact": "Inert and naturally abundant. Crystalline form hazardous if inhaled (silicosis).",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Glass, optical fibers, semiconductors, abrasive, filler, piezoelectric devices.",
    "industrial_production_method": "Naturally abundant as quartz, sand, flint.",
    "notes": "Giant covalent structure. Each Si bonded tetrahedrally to 4 O. Very high MP. HF is only acid that attacks it: SiO2 + 4HF → SiF4 + 2H2O",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "SiCl4",
    "name_common": "Silicon tetrachloride",
    "name_iupac": "Tetrachlorosilane",
    "cas_number": "10026-04-7",
    "primary_element_atomic_number": 14,
    "primary_element_symbol": "Si",
    "oxidation_state_of_element": 4,
    "compound_class": "halide",
    "molecular_mass": 169.90,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless fuming liquid",
    "odor": "Pungent, suffocating",
    "melting_point": 204.0,
    "boiling_point": 330.8,
    "density": 1.52,
    "solubility_in_water": "reacts",
    "molecular_geometry": "tetrahedral",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "109.5°",
    "vsepr_notation": "AX4",
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Lewis acid. Hydrolyzes readily unlike CCl4: SiCl4 + 2H2O → SiO2 + 4HCl. Available 3d orbitals allow hydrolysis.",
    "std_enthalpy_formation": -687.0,
    "std_gibbs_free_energy": -619.8,
    "std_entropy": 239.7,
    "lattice_energy": None,
    "ghs_hazard_codes": "H314, H331, H335",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Reacts with moisture to release HCl. Corrosive to environment.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Semiconductor production, silicone synthesis, optical fiber production.",
    "industrial_production_method": "Si + 2Cl2 → SiCl4",
    "notes": "Key difference from CCl4: SiCl4 hydrolyzes (3d orbitals available), CCl4 does not.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── PHOSPHORUS (Z=15) ───────────────────────────────────────
  {
    "formula": "P4O10",
    "name_common": "Phosphorus pentoxide",
    "name_iupac": "Tetraphosphorus decaoxide",
    "cas_number": "1314-56-3",
    "primary_element_atomic_number": 15,
    "primary_element_symbol": "P",
    "oxidation_state_of_element": 5,
    "compound_class": "oxide",
    "molecular_mass": 283.89,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White fluffy powder",
    "odor": "Odorless",
    "melting_point": 613.0,
    "boiling_point": 633.0,
    "density": 2.30,
    "solubility_in_water": "reacts",
    "molecular_geometry": "cage structure",
    "electron_pair_geometry": "tetrahedral at each P",
    "hybridization": "sp3",
    "bond_angle": "101.6° (P-O-P bridging)",
    "vsepr_notation": None,
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strongly acidic oxide. P4O10 + 6H2O → 4H3PO4. Most powerful common desiccant.",
    "std_enthalpy_formation": -2984.0,
    "std_gibbs_free_energy": -2697.0,
    "std_entropy": 228.9,
    "lattice_energy": None,
    "ghs_hazard_codes": "H260, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Reacts with moisture releasing phosphoric acid. Corrosive.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Desiccant (drying agent), dehydrating agent, H3PO4 production.",
    "industrial_production_method": "P4 + 5O2 → P4O10",
    "notes": "Cage structure. Each P in tetrahedral environment bonded to 4 O. Most acidic Period 3 oxide.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "PCl3",
    "name_common": "Phosphorus trichloride",
    "name_iupac": "Trichlorophosphane",
    "cas_number": "7719-12-2",
    "primary_element_atomic_number": 15,
    "primary_element_symbol": "P",
    "oxidation_state_of_element": 3,
    "compound_class": "halide",
    "molecular_mass": 137.33,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless fuming liquid",
    "odor": "Pungent, suffocating",
    "melting_point": 161.2,
    "boiling_point": 349.0,
    "density": 1.574,
    "solubility_in_water": "reacts",
    "molecular_geometry": "trigonal pyramidal",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "100°",
    "vsepr_notation": "AX3E1",
    "is_polar": True,
    "dipole_moment": 0.97,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Hydrolyzes: PCl3 + 3H2O → H3PO3 + 3HCl",
    "std_enthalpy_formation": -319.7,
    "std_gibbs_free_energy": -272.3,
    "std_entropy": 217.1,
    "lattice_energy": None,
    "ghs_hazard_codes": "H300, H314, H330, H400",
    "nfpa_health": 4, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": 550.0,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Very toxic to aquatic life. Reacts with water to produce HCl.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Chemical synthesis, pesticide production, pharmaceuticals.",
    "industrial_production_method": "P4 + 6Cl2 → 4PCl3",
    "notes": "Trigonal pyramidal (VSEPR: 3 bonding pairs + 1 lone pair). One lone pair on P.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "PCl5",
    "name_common": "Phosphorus pentachloride",
    "name_iupac": "Pentachlorophosphorane",
    "cas_number": "10026-13-8",
    "primary_element_atomic_number": 15,
    "primary_element_symbol": "P",
    "oxidation_state_of_element": 5,
    "compound_class": "halide",
    "molecular_mass": 208.24,
    "physical_state_298k": "solid",
    "color": "white",
    "appearance": "White crystalline solid, fumes in air",
    "odor": "Pungent, HCl-like",
    "melting_point": 440.6,
    "boiling_point": 433.0,
    "density": 1.6,
    "solubility_in_water": "reacts",
    "molecular_geometry": "trigonal bipyramidal",
    "electron_pair_geometry": "trigonal bipyramidal",
    "hybridization": "sp3d",
    "bond_angle": "90° (axial), 120° (equatorial)",
    "vsepr_notation": "AX5",
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": None,
    "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Hydrolyzes in stages: PCl5 + H2O → POCl3 + 2HCl; PCl5 + 4H2O → H3PO4 + 5HCl",
    "std_enthalpy_formation": -374.9,
    "std_gibbs_free_energy": -305.0,
    "std_entropy": 364.6,
    "lattice_energy": None,
    "ghs_hazard_codes": "H260, H300, H314, H330",
    "nfpa_health": 4, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": 660.0,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Very toxic. Produces HCl on contact with moisture.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Chlorinating agent in organic synthesis, catalyst.",
    "industrial_production_method": "PCl3 + Cl2 → PCl5",
    "notes": "TBP in gas phase (sp3d). Ionic in solid: [PCl4]+[PCl6]-. Key example of expanded octet.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "H3PO4",
    "name_common": "Phosphoric acid",
    "name_iupac": "Phosphoric acid",
    "cas_number": "7664-38-2",
    "primary_element_atomic_number": 15,
    "primary_element_symbol": "P",
    "oxidation_state_of_element": 5,
    "compound_class": "oxoacid",
    "molecular_mass": 97.99,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless viscous liquid or transparent crystals",
    "odor": "Odorless",
    "melting_point": 315.5,
    "boiling_point": 431.0,
    "density": 1.885,
    "solubility_in_water": "soluble",
    "molecular_geometry": "tetrahedral",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "109.5°",
    "vsepr_notation": "AX4",
    "is_polar": True,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Triprotic weak acid. pKa1=2.15, pKa2=7.20, pKa3=12.35. Weaker than H2SO4.",
    "std_enthalpy_formation": -1271.7,
    "std_gibbs_free_energy": -1123.6,
    "std_entropy": 150.8,
    "lattice_energy": None,
    "ghs_hazard_codes": "H290, H314",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 1530.0,
    "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Causes eutrophication of water bodies. Major component of fertilizer runoff.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fertilizers (80% of production), food additive (E338, cola drinks), rust removal, pharmaceuticals.",
    "industrial_production_method": "Wet process: Ca3(PO4)2 + 3H2SO4 → 2H3PO4 + 3CaSO4",
    "notes": "Triprotic acid. Less acidic than H2SO4. Used in food (safe). Important in biochemistry (ATP, DNA backbone).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── SULFUR (Z=16) ───────────────────────────────────────────
  {
    "formula": "SO2",
    "name_common": "Sulfur dioxide",
    "name_iupac": "Sulfur dioxide",
    "cas_number": "7446-09-5",
    "primary_element_atomic_number": 16,
    "primary_element_symbol": "S",
    "oxidation_state_of_element": 4,
    "compound_class": "oxide",
    "molecular_mass": 64.06,
    "physical_state_298k": "gas",
    "color": "colorless",
    "appearance": "Colorless gas",
    "odor": "Pungent, suffocating",
    "melting_point": 200.0,
    "boiling_point": 263.1,
    "density": 0.002619,
    "solubility_in_water": "soluble",
    "molecular_geometry": "bent",
    "electron_pair_geometry": "trigonal planar",
    "hybridization": "sp2",
    "bond_angle": "119°",
    "vsepr_notation": "AX2E1",
    "is_polar": True,
    "dipole_moment": 1.63,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Acidic oxide. SO2 + H2O ⇌ H2SO3 (sulfurous acid). Weak diprotic acid formed.",
    "std_enthalpy_formation": -296.8,
    "std_gibbs_free_energy": -300.2,
    "std_entropy": 248.2,
    "lattice_energy": None,
    "ghs_hazard_codes": "H331, H400",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Major air pollutant. Causes acid rain (SO2 → H2SO4). Damages ecosystems, buildings.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "H2SO4 production (Contact process), food preservative (E220), refrigerant, bleaching.",
    "industrial_production_method": "S + O2 → SO2 or as byproduct of metal smelting.",
    "notes": "Bent molecule. Resonance structures. Intermediate in acid rain formation and Contact process.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "SO3",
    "name_common": "Sulfur trioxide",
    "name_iupac": "Sulfur trioxide",
    "cas_number": "7446-11-9",
    "primary_element_atomic_number": 16,
    "primary_element_symbol": "S",
    "oxidation_state_of_element": 6,
    "compound_class": "oxide",
    "molecular_mass": 80.06,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless fuming liquid or solid below 17°C",
    "odor": "Pungent, choking",
    "melting_point": 289.9,
    "boiling_point": 317.9,
    "density": 1.92,
    "solubility_in_water": "reacts",
    "molecular_geometry": "trigonal planar",
    "electron_pair_geometry": "trigonal planar",
    "hybridization": "sp2",
    "bond_angle": "120°",
    "vsepr_notation": "AX3",
    "is_polar": False,
    "dipole_moment": 0.0,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strongly acidic oxide. SO3 + H2O → H2SO4. Most acidic oxide of Period 3 main group elements.",
    "std_enthalpy_formation": -395.7,
    "std_gibbs_free_energy": -371.1,
    "std_entropy": 256.8,
    "lattice_energy": None,
    "ghs_hazard_codes": "H260, H314, H331",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Extremely reactive. Reacts with atmospheric moisture to form H2SO4 aerosols.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Key intermediate in H2SO4 production via Contact process. Dissolved in H2SO4 to form oleum.",
    "industrial_production_method": "Contact process: 2SO2 + O2 → 2SO3 (V2O5 catalyst, 450°C)",
    "notes": "Trigonal planar monomer. Highly reactive. Dissolved in H2SO4 → oleum (fuming sulfuric acid).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "H2SO4",
    "name_common": "Sulfuric acid",
    "name_iupac": "Sulfuric acid",
    "cas_number": "7664-93-9",
    "primary_element_atomic_number": 16,
    "primary_element_symbol": "S",
    "oxidation_state_of_element": 6,
    "compound_class": "oxoacid",
    "molecular_mass": 98.08,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless oily liquid",
    "odor": "Odorless (pure)",
    "melting_point": 283.5,
    "boiling_point": 610.0,
    "density": 1.84,
    "solubility_in_water": "soluble",
    "molecular_geometry": "tetrahedral",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "109.5°",
    "vsepr_notation": "AX4",
    "is_polar": True,
    "dipole_moment": 2.72,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strong diprotic acid. pKa1=-3 (strong), pKa2=1.99. First dissociation complete. Strong dehydrating and oxidizing agent.",
    "std_enthalpy_formation": -814.0,
    "std_gibbs_free_energy": -690.0,
    "std_entropy": 156.9,
    "lattice_energy": None,
    "ghs_hazard_codes": "H290, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": 2140.0,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Causes acid rain. Highly corrosive to ecosystems. Major industrial pollutant if released.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fertilizers (60%), batteries, pharmaceuticals, dyes, detergents. Most produced industrial chemical.",
    "industrial_production_method": "Contact process: S→SO2→SO3→H2SO4. Global production ~200 million tonnes/year.",
    "notes": "King of chemicals. Highest production volume globally. Dehydrates sugar: C12H22O11 → 12C + 11H2O",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "H2S",
    "name_common": "Hydrogen sulfide",
    "name_iupac": "Hydrogen sulfide",
    "cas_number": "7783-06-4",
    "primary_element_atomic_number": 16,
    "primary_element_symbol": "S",
    "oxidation_state_of_element": -2,
    "compound_class": "hydride",
    "molecular_mass": 34.08,
    "physical_state_298k": "gas",
    "color": "colorless",
    "appearance": "Colorless gas",
    "odor": "Rotten eggs (extremely pungent)",
    "melting_point": 187.7,
    "boiling_point": 213.6,
    "density": 0.001363,
    "solubility_in_water": "soluble",
    "molecular_geometry": "bent",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "92°",
    "vsepr_notation": "AX2E2",
    "is_polar": True,
    "dipole_moment": 0.97,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Weak diprotic acid. pKa1=7.0, pKa2=17. Much weaker than H2O in acidity context.",
    "std_enthalpy_formation": -20.6,
    "std_gibbs_free_energy": -33.4,
    "std_entropy": 205.8,
    "lattice_energy": None,
    "ghs_hazard_codes": "H220, H280, H330, H400, H410",
    "nfpa_health": 4, "nfpa_flammability": 4, "nfpa_reactivity": 0,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Extremely toxic to aquatic life. Natural volcanic emission. Smells at 0.5 ppb.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Analytical chemistry (metal ion precipitation), sulfur production, chemical synthesis.",
    "industrial_production_method": "Byproduct of petroleum refining and volcanic activity.",
    "notes": "Bond angle 92° (smaller than H2O 104.5° due to larger S atom, less repulsion). Extremely toxic — paralyzes olfactory nerve at high conc.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── CHLORINE (Z=17) ─────────────────────────────────────────
  {
    "formula": "HCl",
    "name_common": "Hydrogen chloride",
    "name_iupac": "Hydrogen chloride",
    "cas_number": "7647-01-0",
    "primary_element_atomic_number": 17,
    "primary_element_symbol": "Cl",
    "oxidation_state_of_element": -1,
    "compound_class": "hydride",
    "molecular_mass": 36.46,
    "physical_state_298k": "gas",
    "color": "colorless",
    "appearance": "Colorless gas, fumes in moist air",
    "odor": "Sharp, pungent",
    "melting_point": 158.9,
    "boiling_point": 188.1,
    "density": 0.001639,
    "solubility_in_water": "soluble",
    "molecular_geometry": "linear",
    "electron_pair_geometry": "linear",
    "hybridization": "sp",
    "bond_angle": "180°",
    "vsepr_notation": "AX2",
    "is_polar": True,
    "dipole_moment": 1.08,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strong acid in water (hydrochloric acid). pKa = -7. Fully dissociates: HCl → H+ + Cl-",
    "std_enthalpy_formation": -92.3,
    "std_gibbs_free_energy": -95.3,
    "std_entropy": 186.9,
    "lattice_energy": None,
    "ghs_hazard_codes": "H280, H314, H331, H335",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to respiratory system. Contributes to acid deposition.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "PVC production, pH control, metal cleaning, food industry (E507), pharmaceutical synthesis.",
    "industrial_production_method": "H2 + Cl2 → 2HCl or as byproduct of chlorination reactions.",
    "notes": "Linear diatomic. Bond length 127pm. Strong acid in water. Bond enthalpy 432 kJ/mol.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "HClO",
    "name_common": "Hypochlorous acid",
    "name_iupac": "Hypochlorous acid",
    "cas_number": "7790-92-3",
    "primary_element_atomic_number": 17,
    "primary_element_symbol": "Cl",
    "oxidation_state_of_element": 1,
    "compound_class": "oxoacid",
    "molecular_mass": 52.46,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Pale yellow aqueous solution only (pure form unstable)",
    "odor": "Chlorine-like",
    "melting_point": None,
    "boiling_point": None,
    "density": None,
    "solubility_in_water": "soluble",
    "molecular_geometry": "bent",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "103°",
    "vsepr_notation": "AX2E2",
    "is_polar": True,
    "dipole_moment": 1.3,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Weakest chlorine oxoacid. pKa = 7.53. Only 1 oxygen → least electron withdrawal from Cl-O-H.",
    "std_enthalpy_formation": -120.9,
    "std_gibbs_free_energy": -79.9,
    "std_entropy": 142.0,
    "lattice_energy": None,
    "ghs_hazard_codes": "H290, H314, H400",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Reactive oxidant. Toxic to aquatic organisms.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Disinfectant, bleaching agent, water treatment (active component of chlorine in pools).",
    "industrial_production_method": "Cl2 + H2O ⇌ HCl + HClO (disproportionation)",
    "notes": "Weakest of HClO series. Pauling rules: each additional O increases acidity. HClO < HClO2 < HClO3 < HClO4.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "HClO4",
    "name_common": "Perchloric acid",
    "name_iupac": "Perchloric acid",
    "cas_number": "7601-90-3",
    "primary_element_atomic_number": 17,
    "primary_element_symbol": "Cl",
    "oxidation_state_of_element": 7,
    "compound_class": "oxoacid",
    "molecular_mass": 100.46,
    "physical_state_298k": "liquid",
    "color": "colorless",
    "appearance": "Colorless fuming liquid",
    "odor": "Odorless",
    "melting_point": 171.0,
    "boiling_point": 383.0,
    "density": 1.768,
    "solubility_in_water": "soluble",
    "molecular_geometry": "tetrahedral",
    "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3",
    "bond_angle": "109.5°",
    "vsepr_notation": "AX4",
    "is_polar": True,
    "dipole_moment": None,
    "coordination_number": None,
    "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strongest common acid. pKa = -10. Stronger than H2SO4, HNO3, HCl. 3 additional O atoms maximally withdraw electrons.",
    "std_enthalpy_formation": -40.6,
    "std_gibbs_free_energy": None,
    "std_entropy": None,
    "lattice_energy": None,
    "ghs_hazard_codes": "H271, H290, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 3,
    "ld50_mg_kg": None,
    "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Persistent in environment. Toxic. Contaminates groundwater.",
    "biodegradable": False,
    "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Rocket propellant oxidizer (ammonium perchlorate), analytical chemistry, electroplating.",
    "industrial_production_method": "Electrolytic oxidation of NaClO3 → NaClO4 → HClO4",
    "notes": "Strongest of the oxoacids. Demonstrates Pauling rules perfectly. Non-coordinating anion in chemistry.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
]

def seed_compounds():
    print("Starting seed...")
    try:
        with engine.connect() as conn:
            print("Connected to database.")
            result = conn.execute(text("SELECT COUNT(*) FROM compounds"))
            count = result.scalar()
            print(f"Current compound count: {count}")
            
            if count > 0:
                print(f"Clearing {count} existing entries...")
                conn.execute(text("DELETE FROM compounds"))
                conn.commit()

            print(f"Inserting {len(COMPOUNDS)} compounds...")
            for i, c in enumerate(COMPOUNDS):
                cols = ', '.join(c.keys())
                vals = ', '.join([f":{k}" for k in c.keys()])
                sql = text(f"INSERT INTO compounds ({cols}) VALUES ({vals})")
                conn.execute(sql, c)
                print(f"  Inserted: {c['formula']}")

            conn.commit()
            print(f"Done. Successfully seeded {len(COMPOUNDS)} compounds.")
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    seed_compounds()