import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from sqlalchemy import create_engine, text
from dotenv import load_dotenv

load_dotenv()
DATABASE_URL = os.getenv("DATABASE_URL")
engine = create_engine(DATABASE_URL)

COMPOUNDS = [

  # ── GROUP 1: LITHIUM (Z=3) ──────────────────────────────────
  {
    "formula": "LiOH", "name_common": "Lithium hydroxide",
    "name_iupac": "Lithium hydroxide", "cas_number": "1310-65-2",
    "primary_element_atomic_number": 3, "primary_element_symbol": "Li",
    "oxidation_state_of_element": 1, "compound_class": "hydroxide",
    "molecular_mass": 23.95, "physical_state_298k": "solid", "color": "white",
    "appearance": "White monoclinic crystals", "odor": "Odorless",
    "melting_point": 744.0, "boiling_point": 1597.0, "density": 1.46,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Strong base. Fully dissociates. Used to absorb CO2: LiOH + CO2 → LiHCO3. Most efficient CO2 absorber per kg due to low molecular weight.",
    "std_enthalpy_formation": -484.9, "std_gibbs_free_energy": -439.0,
    "std_entropy": 42.8, "lattice_energy": None,
    "ghs_hazard_codes": "H290, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Corrosive to aquatic organisms at high concentrations.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "CO2 scrubber in spacecraft (Apollo) and submarines, lithium grease, batteries.",
    "industrial_production_method": "2Li + 2H2O → 2LiOH + H2",
    "notes": "Despite being a strong base, lower molecular weight than NaOH makes it more efficient CO2 absorber per kg. NASA uses LiOH canisters in spacecraft.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Li2O", "name_common": "Lithium oxide",
    "name_iupac": "Dilithium oxide", "cas_number": "12057-24-8",
    "primary_element_atomic_number": 3, "primary_element_symbol": "Li",
    "oxidation_state_of_element": 1, "compound_class": "oxide",
    "molecular_mass": 29.88, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline powder", "odor": "Odorless",
    "melting_point": 1843.0, "boiling_point": None, "density": 2.013,
    "solubility_in_water": "reacts",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Reacts with water: Li2O + H2O → 2LiOH.",
    "std_enthalpy_formation": -597.9, "std_gibbs_free_energy": -561.2,
    "std_entropy": 37.6, "lattice_energy": -2814.0,
    "ghs_hazard_codes": "H260, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Reacts with moisture to form corrosive LiOH.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Nuclear reactor moderator, ceramic glass production.",
    "industrial_production_method": "4Li + O2 → 2Li2O (controlled oxygen)",
    "notes": "Unlike Na which forms Na2O2 (peroxide) in excess O2, Li forms Li2O. Anomalous behavior of Li compared to heavier alkali metals due to small cation size.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "LiCl", "name_common": "Lithium chloride",
    "name_iupac": "Lithium chloride", "cas_number": "7447-41-8",
    "primary_element_atomic_number": 3, "primary_element_symbol": "Li",
    "oxidation_state_of_element": 1, "compound_class": "halide",
    "molecular_mass": 42.39, "physical_state_298k": "solid", "color": "white",
    "appearance": "White cubic crystals", "odor": "Odorless",
    "melting_point": 878.0, "boiling_point": 1655.0, "density": 2.068,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. pH ≈ 7.",
    "std_enthalpy_formation": -408.6, "std_gibbs_free_energy": -384.4,
    "std_entropy": 59.3, "lattice_energy": -853.0,
    "ghs_hazard_codes": "H302, H312, H315, H319, H332, H335",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 526.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Moderately toxic to aquatic life.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Air conditioning desiccant, flux for welding aluminium, lithium metal production, red flame colorant.",
    "industrial_production_method": "Li2CO3 + 2HCl → 2LiCl + H2O + CO2",
    "notes": "Anomalously high lattice energy for Group 1 halide due to small Li+ radius. Unusually soluble in polar organic solvents — covalent character due to Fajans' rules. Crimson-red flame test.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Li2CO3", "name_common": "Lithium carbonate",
    "name_iupac": "Dilithium carbonate", "cas_number": "554-13-2",
    "primary_element_atomic_number": 3, "primary_element_symbol": "Li",
    "oxidation_state_of_element": 1, "compound_class": "salt",
    "molecular_mass": 73.89, "physical_state_298k": "solid", "color": "white",
    "appearance": "White monoclinic crystals", "odor": "Odorless",
    "melting_point": 996.0, "boiling_point": None, "density": 2.11,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic salt. pH ≈ 11-12. Anomalously sparingly soluble unlike other Group 1 carbonates (diagonal relationship with Mg).",
    "std_enthalpy_formation": -1215.9, "std_gibbs_free_energy": -1132.1,
    "std_entropy": 90.4, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H361",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 525.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic life. Avoid environmental release.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Psychiatric medication for bipolar disorder, ceramic and glass production, lithium-ion battery cathodes.",
    "industrial_production_method": "From lithium brines by precipitation with Na2CO3.",
    "notes": "Anomalous: sparingly soluble unlike Na2CO3/K2CO3. Li resembles Mg (diagonal relationship). Essential WHO medicine for bipolar disorder. Key precursor for all Li battery materials.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── GROUP 1: POTASSIUM (Z=19) ────────────────────────────────
  {
    "formula": "KOH", "name_common": "Potassium hydroxide",
    "name_iupac": "Potassium hydroxide", "cas_number": "1310-58-3",
    "primary_element_atomic_number": 19, "primary_element_symbol": "K",
    "oxidation_state_of_element": 1, "compound_class": "hydroxide",
    "molecular_mass": 56.11, "physical_state_298k": "solid", "color": "white",
    "appearance": "White deliquescent pellets or flakes", "odor": "Odorless",
    "melting_point": 633.0, "boiling_point": 1600.0, "density": 2.04,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Strong base. Fully dissociates. Slightly stronger and more soluble in ethanol than NaOH.",
    "std_enthalpy_formation": -424.6, "std_gibbs_free_energy": -378.9,
    "std_entropy": 81.2, "lattice_energy": None,
    "ghs_hazard_codes": "H290, H302, H314",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": 284.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Raises pH of water bodies. Harmful to aquatic life.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": 1807,
    "uses": "Soap making (soft/liquid soap), biodiesel production, alkaline batteries (KOH electrolyte), food additive E525.",
    "industrial_production_method": "Chloralkali process: 2KCl + 2H2O → Cl2 + H2 + 2KOH",
    "notes": "Caustic potash. Makes soft (liquid) soap — contrast with NaOH which makes hard soap. Discovered by Davy in 1807 by electrolysis.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "KCl", "name_common": "Potassium chloride",
    "name_iupac": "Potassium chloride", "cas_number": "7447-40-7",
    "primary_element_atomic_number": 19, "primary_element_symbol": "K",
    "oxidation_state_of_element": 1, "compound_class": "halide",
    "molecular_mass": 74.55, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline solid", "odor": "Odorless",
    "melting_point": 1044.0, "boiling_point": 1686.0, "density": 1.984,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. pH ≈ 7.",
    "std_enthalpy_formation": -436.5, "std_gibbs_free_energy": -408.5,
    "std_entropy": 82.6, "lattice_energy": -715.0,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 2500.0, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Generally safe. Important plant nutrient.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fertilizer (potash), salt substitute, lethal injection component, food additive E508, KOH production.",
    "industrial_production_method": "Mining of sylvite deposits or sea water evaporation.",
    "notes": "NaCl-type structure. Flame test: violet/lilac. Essential plant nutrient (K). Major no-salt substitute product.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "KNO3", "name_common": "Potassium nitrate",
    "name_iupac": "Potassium nitrate", "cas_number": "7757-79-1",
    "primary_element_atomic_number": 19, "primary_element_symbol": "K",
    "oxidation_state_of_element": 1, "compound_class": "salt",
    "molecular_mass": 101.10, "physical_state_298k": "solid", "color": "white",
    "appearance": "White rhombic crystals", "odor": "Odorless",
    "melting_point": 607.0, "boiling_point": None, "density": 2.11,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. Mildly oxidizing. pH ≈ 7.",
    "std_enthalpy_formation": -494.6, "std_gibbs_free_energy": -394.9,
    "std_entropy": 133.1, "lattice_energy": None,
    "ghs_hazard_codes": "H272, H315, H319, H335",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 2,
    "ld50_mg_kg": 3750.0, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Can cause eutrophication. Contributes to nitrogen cycle.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fertilizer (N and K source), gunpowder (75% KNO3 + 15% C + 10% S), food preservative E252, fireworks.",
    "industrial_production_method": "KCl + HNO3 → KNO3 + HCl",
    "notes": "Saltpeter or nitre. Black powder ingredient. Decomposes on heating: 2KNO3 → 2KNO2 + O2 at 400°C.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "KMnO4", "name_common": "Potassium permanganate",
    "name_iupac": "Potassium permanganate", "cas_number": "7722-64-7",
    "primary_element_atomic_number": 19, "primary_element_symbol": "K",
    "oxidation_state_of_element": 1, "compound_class": "salt",
    "molecular_mass": 158.03, "physical_state_298k": "solid",
    "color": "dark purple", "appearance": "Dark purple to black metallic crystals",
    "odor": "Odorless", "melting_point": None, "boiling_point": None,
    "density": 2.703, "solubility_in_water": "soluble",
    "molecular_geometry": "ionic (MnO4- tetrahedral)", "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3 (Mn in MnO4-)", "bond_angle": "109.5°",
    "vsepr_notation": "AX4", "is_polar": False, "dipole_moment": 0.0,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Powerful oxidizing agent. MnO4- reduced differently by pH: acid→Mn2+ (colorless), neutral→MnO2 (brown ppt), alkaline→MnO4²- (green). Self-indicating in titrations.",
    "std_enthalpy_formation": -837.2, "std_gibbs_free_energy": -737.6,
    "std_entropy": 171.7, "lattice_energy": None,
    "ghs_hazard_codes": "H272, H290, H302, H400, H410",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 3,
    "ld50_mg_kg": 1090.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic organisms. Strong oxidant damages ecosystems.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": 1659,
    "uses": "Water purification, disinfectant, oxidizing agent in organic synthesis, analytical titrations, wound treatment.",
    "industrial_production_method": "MnO2 + KOH → K2MnO4 → KMnO4 (electrolytic oxidation)",
    "notes": "Mn is in +7 state. Intense purple — self-indicator (colorless → pink endpoint in titrations). Color change with pH: purple (acid)→colorless (Mn2+); purple (neutral)→brown MnO2; purple (alkali)→green MnO4²-. Discovered 1659 by Glauber.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "K2Cr2O7", "name_common": "Potassium dichromate",
    "name_iupac": "Dipotassium dichromate", "cas_number": "7778-50-9",
    "primary_element_atomic_number": 19, "primary_element_symbol": "K",
    "oxidation_state_of_element": 1, "compound_class": "salt",
    "molecular_mass": 294.18, "physical_state_298k": "solid",
    "color": "orange", "appearance": "Bright orange-red triclinic crystals",
    "odor": "Odorless", "melting_point": 671.0, "boiling_point": None,
    "density": 2.676, "solubility_in_water": "soluble",
    "molecular_geometry": "two tetrahedra sharing O (Cr2O7²-)", "electron_pair_geometry": "tetrahedral at each Cr",
    "hybridization": "sp3 (Cr)", "bond_angle": "126° (Cr-O-Cr)",
    "vsepr_notation": None, "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. Strong oxidizing agent. In acid: Cr2O7²- + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H2O (orange→green). In alkali: converts to CrO4²- (yellow). Chromate-dichromate equilibrium pH-dependent.",
    "std_enthalpy_formation": -2061.5, "std_gibbs_free_energy": -1881.8,
    "std_entropy": 291.2, "lattice_energy": None,
    "ghs_hazard_codes": "H271, H301, H312, H330, H334, H340, H350, H360, H372, H400, H410",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 3,
    "ld50_mg_kg": 25.0, "is_toxic": True, "is_carcinogenic": True,
    "environmental_impact": "Cr(VI) — extremely toxic, persistent, carcinogenic. Major environmental hazard.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": 1798,
    "uses": "Analytical chemistry oxidimetry, leather tanning, wood preservation. Being phased out due to toxicity.",
    "industrial_production_method": "4FeCr2O4 + 8Na2CO3 + 7O2 → 8Na2CrO4... then acidify and convert with KCl.",
    "notes": "Cr(VI) — known carcinogen. Classic oxidizing agent. Cr2O7²- (orange) + H2O ⇌ 2CrO4²- + 2H⁺ (yellow) — pH-controlled equilibrium. Being replaced by greener alternatives in industry.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── GROUP 2: BERYLLIUM (Z=4) ─────────────────────────────────
  {
    "formula": "BeO", "name_common": "Beryllium oxide",
    "name_iupac": "Beryllium oxide", "cas_number": "1304-56-9",
    "primary_element_atomic_number": 4, "primary_element_symbol": "Be",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 25.01, "physical_state_298k": "solid", "color": "white",
    "appearance": "White powder", "odor": "Odorless",
    "melting_point": 2780.0, "boiling_point": 3769.0, "density": 3.01,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice (wurtzite)", "electron_pair_geometry": "tetrahedral",
    "hybridization": "sp3", "bond_angle": "109.5°", "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 4, "ligands": None,
    "is_acid": True, "is_base": True, "is_amphoteric": True,
    "acid_base_notes": "Amphoteric oxide (diagonal relationship with Al2O3). With acid: BeO + H2SO4 → BeSO4 + H2O. With alkali: BeO + 2NaOH + H2O → Na2[Be(OH)4].",
    "std_enthalpy_formation": -609.4, "std_gibbs_free_energy": -580.1,
    "std_entropy": 13.8, "lattice_energy": -4443.0,
    "ghs_hazard_codes": "H301, H315, H317, H319, H330, H350, H372",
    "nfpa_health": 4, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": True,
    "environmental_impact": "Extremely toxic and carcinogenic. Causes berylliosis (fatal lung disease).",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Nuclear reactor components, X-ray windows, specialized ceramics, microelectronics.",
    "industrial_production_method": "Calcination of Be(OH)2 or BeCO3.",
    "notes": "Amphoteric — diagonal relationship with Al2O3. Very high thermal conductivity (250 W/m·K) despite being non-metal. Extreme toxicity limits industrial use.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Be(OH)2", "name_common": "Beryllium hydroxide",
    "name_iupac": "Beryllium dihydroxide", "cas_number": "13327-32-7",
    "primary_element_atomic_number": 4, "primary_element_symbol": "Be",
    "oxidation_state_of_element": 2, "compound_class": "hydroxide",
    "molecular_mass": 43.03, "physical_state_298k": "solid", "color": "white",
    "appearance": "White amorphous powder", "odor": "Odorless",
    "melting_point": None, "boiling_point": None, "density": 1.92,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": True, "is_base": True, "is_amphoteric": True,
    "acid_base_notes": "Amphoteric hydroxide. As base: Be(OH)2 + H2SO4 → BeSO4 + 2H2O. As acid: Be(OH)2 + 2NaOH → Na2[Be(OH)4]. Resembles Al(OH)3 — diagonal relationship.",
    "std_enthalpy_formation": -902.5, "std_gibbs_free_energy": -815.0,
    "std_entropy": 51.9, "lattice_energy": None,
    "ghs_hazard_codes": "H301, H315, H317, H330, H334, H350, H372",
    "nfpa_health": 4, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": True,
    "environmental_impact": "Extremely toxic. All Be compounds considered carcinogenic.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Intermediate in Be metal production.",
    "industrial_production_method": "BeSO4 + 2NaOH → Be(OH)2 + Na2SO4",
    "notes": "Classic amphoteric hydroxide. Resembles Al(OH)3 due to Be-Al diagonal relationship. Berylliosis: fatal chronic lung disease from Be dust inhalation.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "BeCl2", "name_common": "Beryllium chloride",
    "name_iupac": "Beryllium dichloride", "cas_number": "7787-47-5",
    "primary_element_atomic_number": 4, "primary_element_symbol": "Be",
    "oxidation_state_of_element": 2, "compound_class": "halide",
    "molecular_mass": 79.92, "physical_state_298k": "solid", "color": "white",
    "appearance": "White hygroscopic crystals", "odor": "Odorless",
    "melting_point": 678.0, "boiling_point": 793.0, "density": 1.899,
    "solubility_in_water": "reacts",
    "molecular_geometry": "linear (monomer, gas phase)", "electron_pair_geometry": "linear",
    "hybridization": "sp", "bond_angle": "180°", "vsepr_notation": "AX2",
    "is_polar": False, "dipole_moment": 0.0,
    "coordination_number": 2, "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Strong Lewis acid. Electron-deficient (only 4 electrons around Be, incomplete octet). Readily accepts lone pairs from donor molecules.",
    "std_enthalpy_formation": -490.4, "std_gibbs_free_energy": -445.6,
    "std_entropy": 75.8, "lattice_energy": -3003.0,
    "ghs_hazard_codes": "H300, H314, H317, H330, H334, H350, H372",
    "nfpa_health": 4, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": True,
    "environmental_impact": "Extremely toxic.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Preparation of Be metal, Lewis acid catalyst.",
    "industrial_production_method": "BeO + Cl2 + C → BeCl2 + CO at high temperature.",
    "notes": "Linear in gas phase (sp hybridization) despite being Group 2 — only 4 electrons around Be (electron deficient). Polymeric chain in solid. Strong Lewis acid due to empty p orbital. Diagonal relationship with AlCl3.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── GROUP 2: CALCIUM (Z=20) ──────────────────────────────────
  {
    "formula": "CaO", "name_common": "Calcium oxide",
    "name_iupac": "Calcium oxide", "cas_number": "1305-78-8",
    "primary_element_atomic_number": 20, "primary_element_symbol": "Ca",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 56.08, "physical_state_298k": "solid", "color": "white",
    "appearance": "White granular solid", "odor": "Odorless",
    "melting_point": 3173.0, "boiling_point": 3123.0, "density": 3.35,
    "solubility_in_water": "reacts",
    "molecular_geometry": "ionic lattice (NaCl-type)", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Reacts vigorously with water (ΔH = -65 kJ/mol): CaO + H2O → Ca(OH)2. More basic than MgO.",
    "std_enthalpy_formation": -635.1, "std_gibbs_free_energy": -604.0,
    "std_entropy": 38.2, "lattice_energy": -3401.0,
    "ghs_hazard_codes": "H290, H314, H335",
    "nfpa_health": 3, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Raises soil and water pH. Used in environmental remediation.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Steel production (flux to remove SiO2), cement production, water treatment, soil pH correction.",
    "industrial_production_method": "Thermal decomposition of limestone: CaCO3 → CaO + CO2 above 840°C",
    "notes": "Called quicklime. Highly exothermic hydration — used historically in limelight. Key in cement manufacture (CaO + SiO2 → CaSiO3). More basic than MgO (Group 2 trend).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Ca(OH)2", "name_common": "Calcium hydroxide",
    "name_iupac": "Calcium dihydroxide", "cas_number": "1305-62-0",
    "primary_element_atomic_number": 20, "primary_element_symbol": "Ca",
    "oxidation_state_of_element": 2, "compound_class": "hydroxide",
    "molecular_mass": 74.09, "physical_state_298k": "solid", "color": "white",
    "appearance": "White powder", "odor": "Odorless",
    "melting_point": None, "boiling_point": None, "density": 2.211,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Moderately strong base. Ksp = 4.68×10⁻⁶. Limewater pH ≈ 12.4. More basic than Mg(OH)2 but less than Ba(OH)2.",
    "std_enthalpy_formation": -986.1, "std_gibbs_free_energy": -898.5,
    "std_entropy": 83.4, "lattice_energy": None,
    "ghs_hazard_codes": "H315, H318, H335",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 7340.0, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Raises pH. Used to neutralize acid soils and acid mine drainage.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Building mortar and plaster, water treatment, food processing E526, sugar refining, soil conditioning.",
    "industrial_production_method": "CaO + H2O → Ca(OH)2 (slaking of quicklime)",
    "notes": "Slaked lime or limewater. CO2 test: Ca(OH)2 + CO2 → CaCO3↓ (milky); excess CO2: CaCO3 + CO2 + H2O → Ca(HCO3)2 (clears). Inverse solubility: less soluble when hot.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "CaCO3", "name_common": "Calcium carbonate",
    "name_iupac": "Calcium carbonate", "cas_number": "471-34-1",
    "primary_element_atomic_number": 20, "primary_element_symbol": "Ca",
    "oxidation_state_of_element": 2, "compound_class": "salt",
    "molecular_mass": 100.09, "physical_state_298k": "solid", "color": "white",
    "appearance": "White powder or crystals (chalk, limestone, marble)",
    "odor": "Odorless", "melting_point": 1612.0, "boiling_point": None,
    "density": 2.71, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic salt. Ksp = 3.36×10⁻⁹. Dissolves in acid: CaCO3 + 2HCl → CaCl2 + H2O + CO2↑. Dissolves in excess CO2: CaCO3 + CO2 + H2O → Ca(HCO3)2.",
    "std_enthalpy_formation": -1207.6, "std_gibbs_free_energy": -1129.1,
    "std_entropy": 91.7, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 6450.0, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Naturally abundant. Buffers ocean pH. Ocean acidification dissolves coral (CaCO3).",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Construction (limestone, marble), cement raw material, antacid, calcium supplement, paper filler.",
    "industrial_production_method": "Naturally occurring as limestone, chalk, marble.",
    "notes": "Most abundant Ca compound. Three polymorphs: calcite, aragonite, vaterite. Basis of limestone caves. Coral reefs are CaCO3. Key CO2 indicator reaction.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "CaSO4", "name_common": "Calcium sulfate",
    "name_iupac": "Calcium sulfate", "cas_number": "7778-18-9",
    "primary_element_atomic_number": 20, "primary_element_symbol": "Ca",
    "oxidation_state_of_element": 2, "compound_class": "salt",
    "molecular_mass": 136.14, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline powder", "odor": "Odorless",
    "melting_point": 1733.0, "boiling_point": None, "density": 2.96,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. Ksp = 4.93×10⁻⁵. Very slightly soluble.",
    "std_enthalpy_formation": -1434.5, "std_gibbs_free_energy": -1322.0,
    "std_entropy": 107.4, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Naturally occurring. Generally safe.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Plaster of Paris (CaSO4·½H2O), drywall/gypsum board (CaSO4·2H2O), blackboard chalk, food additive E516.",
    "industrial_production_method": "From gypsum deposits or byproduct of H3PO4 production.",
    "notes": "Hydrated forms: CaSO4·2H2O (gypsum), CaSO4·½H2O (plaster of Paris). Setting reaction: 2(CaSO4·½H2O) + 3H2O → 2(CaSO4·2H2O) with expansion. 'Dead burned' anhydrite cannot reabsorb water.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "CaCl2", "name_common": "Calcium chloride",
    "name_iupac": "Calcium dichloride", "cas_number": "10043-52-4",
    "primary_element_atomic_number": 20, "primary_element_symbol": "Ca",
    "oxidation_state_of_element": 2, "compound_class": "halide",
    "molecular_mass": 110.98, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline solid, deliquescent", "odor": "Odorless",
    "melting_point": 1045.0, "boiling_point": 1935.0, "density": 2.15,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral to slightly acidic salt. pH ≈ 6.8.",
    "std_enthalpy_formation": -795.4, "std_gibbs_free_energy": -748.8,
    "std_entropy": 104.6, "lattice_energy": -2258.0,
    "ghs_hazard_codes": "H302, H318, H319, H335",
    "nfpa_health": 1, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 1000.0, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Can harm vegetation at high concentrations when used as road de-icer.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Road de-icer, food additive (firming agent, E509), desiccant, swimming pool pH adjustment.",
    "industrial_production_method": "Solvay process byproduct: 2NH4Cl + Ca(OH)2 → CaCl2 + 2NH3 + 2H2O",
    "notes": "Highly hygroscopic. Dissolves exothermically. More effective de-icer than NaCl at lower temperatures. Used as desiccant in laboratories.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── GROUP 2: BARIUM (Z=56) ────────────────────────────────────
  {
    "formula": "BaO", "name_common": "Barium oxide",
    "name_iupac": "Barium oxide", "cas_number": "1304-28-5",
    "primary_element_atomic_number": 56, "primary_element_symbol": "Ba",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 153.33, "physical_state_298k": "solid", "color": "white",
    "appearance": "White powder", "odor": "Odorless",
    "melting_point": 2246.0, "boiling_point": None, "density": 5.72,
    "solubility_in_water": "reacts",
    "molecular_geometry": "ionic lattice (NaCl-type)", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Strongly basic oxide. BaO + H2O → Ba(OH)2 (highly exothermic). Most basic of Group 2 oxides.",
    "std_enthalpy_formation": -553.5, "std_gibbs_free_energy": -525.1,
    "std_entropy": 70.4, "lattice_energy": -3054.0,
    "ghs_hazard_codes": "H302, H332",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 1,
    "ld50_mg_kg": 500.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic life.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Manufacture of Ba(OH)2, gas purification.",
    "industrial_production_method": "BaCO3 → BaO + CO2 above 1360°C",
    "notes": "Most basic Group 2 oxide. Trend: BeO (amphoteric) < MgO < CaO < SrO < BaO (increasingly basic). Large Ba2+ has low charge density → ionic bond more polar → more basic oxide.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Ba(OH)2", "name_common": "Barium hydroxide",
    "name_iupac": "Barium dihydroxide", "cas_number": "17194-00-2",
    "primary_element_atomic_number": 56, "primary_element_symbol": "Ba",
    "oxidation_state_of_element": 2, "compound_class": "hydroxide",
    "molecular_mass": 171.34, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline powder", "odor": "Odorless",
    "melting_point": 681.0, "boiling_point": None, "density": 3.743,
    "solubility_in_water": "slightly_soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Strongest soluble Group 2 base. Fully dissociates. pH ≈ 13.3 (0.1M). Stronger than Ca(OH)2.",
    "std_enthalpy_formation": -944.7, "std_gibbs_free_energy": -855.5,
    "std_entropy": 96.4, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H314, H332",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 300.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic life. Corrosive.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Analytical chemistry, manufacture of Ba salts, fat saponification.",
    "industrial_production_method": "BaO + H2O → Ba(OH)2",
    "notes": "Strongest Group 2 hydroxide. Trend: Mg(OH)2 < Ca(OH)2 < Sr(OH)2 < Ba(OH)2. Classic endothermic reaction demo: Ba(OH)2·8H2O + 2NH4SCN — temperature drops to -20°C.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "BaSO4", "name_common": "Barium sulfate",
    "name_iupac": "Barium sulfate", "cas_number": "7727-43-7",
    "primary_element_atomic_number": 56, "primary_element_symbol": "Ba",
    "oxidation_state_of_element": 2, "compound_class": "salt",
    "molecular_mass": 233.39, "physical_state_298k": "solid", "color": "white",
    "appearance": "White heavy powder", "odor": "Odorless",
    "melting_point": 1776.0, "boiling_point": None, "density": 4.499,
    "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. Ksp = 1.1×10⁻¹⁰. Insoluble even in concentrated acids.",
    "std_enthalpy_formation": -1473.2, "std_gibbs_free_energy": -1362.2,
    "std_entropy": 132.2, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 0, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Inert. Non-toxic despite Ba2+ being toxic — too insoluble to release ions.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Barium meal (medical X-ray contrast agent for GI tract), drilling mud in oil wells, white paint pigment.",
    "industrial_production_method": "BaCl2 + Na2SO4 → BaSO4↓ + 2NaCl or mined as barite.",
    "notes": "Unique toxicology: Ba2+ is highly toxic but BaSO4 is safe to swallow for X-ray imaging because Ksp is so small no toxic Ba2+ is released. Proves solubility determines toxicity. Group 2 sulfate solubility: MgSO4 > CaSO4 > SrSO4 > BaSO4.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "BaCl2", "name_common": "Barium chloride",
    "name_iupac": "Barium dichloride", "cas_number": "10361-37-2",
    "primary_element_atomic_number": 56, "primary_element_symbol": "Ba",
    "oxidation_state_of_element": 2, "compound_class": "halide",
    "molecular_mass": 208.23, "physical_state_298k": "solid", "color": "white",
    "appearance": "White crystalline solid", "odor": "Odorless",
    "melting_point": 1235.0, "boiling_point": 1833.0, "density": 3.856,
    "solubility_in_water": "soluble",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Neutral salt. Toxic Ba2+ ions released in solution.",
    "std_enthalpy_formation": -858.6, "std_gibbs_free_energy": -810.4,
    "std_entropy": 123.7, "lattice_energy": -2056.0,
    "ghs_hazard_codes": "H302, H332",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 118.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic organisms. Ba2+ is toxic unlike BaSO4.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fireworks (apple-green color), PVC heat stabilizer, test for SO4²- ions.",
    "industrial_production_method": "BaSO4 + 4C → BaS + 4CO; BaS + Cl2 → BaCl2 + S",
    "notes": "Gives apple-green flame test. Used to test for SO4²-: BaCl2 + Na2SO4 → BaSO4↓ (white, insoluble in HCl — confirms sulfate). Contrast with non-toxic BaSO4.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── TRANSITION METALS: IRON (Z=26) ──────────────────────────
  {
    "formula": "Fe2O3", "name_common": "Iron(III) oxide",
    "name_iupac": "Iron(III) oxide", "cas_number": "1309-37-1",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 3, "compound_class": "oxide",
    "molecular_mass": 159.69, "physical_state_298k": "solid",
    "color": "red-brown", "appearance": "Red-brown powder (hematite)",
    "odor": "Odorless", "melting_point": 1838.0, "boiling_point": None,
    "density": 5.24, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice (corundum structure)", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Dissolves in strong acids: Fe2O3 + 6HCl → 2FeCl3 + 3H2O.",
    "std_enthalpy_formation": -824.2, "std_gibbs_free_energy": -742.2,
    "std_entropy": 87.4, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 0, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Naturally abundant (hematite ore). Low environmental impact.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Iron ore for steel production, red pigment, magnetic recording media, thermite.",
    "industrial_production_method": "4Fe + 3O2 → 2Fe2O3 (rusting) or mining hematite.",
    "notes": "Main component of rust. Hematite is most important iron ore. Thermite: Fe2O3 + 2Al → 2Fe + Al2O3 (highly exothermic). Same corundum structure as Al2O3 and Cr2O3.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Fe3O4", "name_common": "Iron(II,III) oxide",
    "name_iupac": "Iron(II,III) oxide", "cas_number": "1317-61-9",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 231.53, "physical_state_298k": "solid",
    "color": "black", "appearance": "Black powder or crystals (magnetite)",
    "odor": "Odorless", "melting_point": 1870.0, "boiling_point": None,
    "density": 5.17, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice (spinel structure)", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Weakly basic. Mixed valence: contains both Fe2+ and Fe3+.",
    "std_enthalpy_formation": -1118.4, "std_gibbs_free_energy": -1015.4,
    "std_entropy": 146.4, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 0, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Natural mineral. Low environmental impact.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Natural magnet (lodestone), magnetic recording media, MRI contrast agent, ferrofluids.",
    "industrial_production_method": "3Fe + 4H2O → Fe3O4 + 4H2 at high temperature",
    "notes": "Magnetite. Naturally magnetic (lodestone — first known magnetic material, used in compasses). Mixed +2/+3 oxidation states: FeO·Fe2O3. Spinel structure. Inverse spinel at room temperature.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "FeO", "name_common": "Iron(II) oxide",
    "name_iupac": "Iron(II) oxide", "cas_number": "1345-25-1",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 71.84, "physical_state_298k": "solid",
    "color": "black", "appearance": "Black powder",
    "odor": "Odorless", "melting_point": 1650.0, "boiling_point": None,
    "density": 5.74, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice (NaCl-type)", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 6, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Dissolves in acids: FeO + H2SO4 → FeSO4 + H2O.",
    "std_enthalpy_formation": -272.0, "std_gibbs_free_energy": -251.4,
    "std_entropy": 60.8, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 0, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Low impact. Natural mineral (wustite).",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Pigment, ceramics, glass coloring.",
    "industrial_production_method": "Fe2O3 + CO → 2FeO + CO2",
    "notes": "Wustite mineral form. Less stable than Fe2O3. NaCl-type structure. Disproportionates: 4FeO → Fe + Fe3O4 above 575°C. Non-stoichiometric composition (Fe0.95O typical).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "FeCl3", "name_common": "Iron(III) chloride",
    "name_iupac": "Iron(III) chloride", "cas_number": "7705-08-0",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 3, "compound_class": "halide",
    "molecular_mass": 162.20, "physical_state_298k": "solid",
    "color": "dark brown", "appearance": "Dark brown/black hygroscopic crystals",
    "odor": "Faint HCl in moist air", "melting_point": 577.0, "boiling_point": 588.0,
    "density": 2.90, "solubility_in_water": "soluble",
    "molecular_geometry": "trigonal planar (monomer)", "electron_pair_geometry": "trigonal planar",
    "hybridization": "sp2", "bond_angle": "120°", "vsepr_notation": "AX3",
    "is_polar": False, "dipole_moment": 0.0,
    "coordination_number": None, "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Lewis acid and Bronsted acid in water. Fe3+ is a strong Lewis acid. Hydrolyzes: FeCl3 + 3H2O → Fe(OH)3 + 3HCl. Solution pH ≈ 2-3.",
    "std_enthalpy_formation": -399.5, "std_gibbs_free_energy": -334.0,
    "std_entropy": 142.3, "lattice_energy": -5359.0,
    "ghs_hazard_codes": "H302, H312, H315, H318, H332, H335",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 1872.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic organisms. Can lower pH of water bodies.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "PCB etching, water treatment (coagulant), catalyst, qualitative analysis.",
    "industrial_production_method": "2Fe + 3Cl2 → 2FeCl3",
    "notes": "Etches copper: 2FeCl3 + Cu → 2FeCl2 + CuCl2. Blood-red color with SCN- (thiocyanate test for Fe3+). Dimerizes as Fe2Cl6 in vapor. Lewis acid catalyst for Friedel-Crafts reactions.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "FeSO4", "name_common": "Iron(II) sulfate",
    "name_iupac": "Iron(II) sulfate", "cas_number": "7720-78-7",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 2, "compound_class": "salt",
    "molecular_mass": 151.91, "physical_state_298k": "solid",
    "color": "white", "appearance": "Pale green crystals (heptahydrate FeSO4·7H2O = green vitriol)",
    "odor": "Odorless", "melting_point": 953.0, "boiling_point": None,
    "density": 2.841, "solubility_in_water": "soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Acidic salt. Fe2+ hydrolyzes: Fe2+ + 2H2O ⇌ Fe(OH)2 + 2H+. pH ≈ 3-4. Mild reducing agent — can be oxidized to Fe3+.",
    "std_enthalpy_formation": -928.4, "std_gibbs_free_energy": -820.8,
    "std_entropy": 107.5, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H318, H411",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 319.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic life at high concentrations.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Iron supplement (anaemia treatment), fertilizer, water treatment, iron gall ink historically.",
    "industrial_production_method": "Fe + H2SO4 → FeSO4 + H2↑",
    "notes": "Green vitriol (FeSO4·7H2O). Pale green color from [Fe(H2O)6]2+. Oxidizes in air to yellow-brown Fe2(SO4)3. Key in Mohr's salt: (NH4)2Fe(SO4)2·6H2O (stable Fe2+ standard).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Fe(OH)3", "name_common": "Iron(III) hydroxide",
    "name_iupac": "Iron(III) hydroxide", "cas_number": "1309-33-7",
    "primary_element_atomic_number": 26, "primary_element_symbol": "Fe",
    "oxidation_state_of_element": 3, "compound_class": "hydroxide",
    "molecular_mass": 106.87, "physical_state_298k": "solid",
    "color": "red-brown", "appearance": "Red-brown gelatinous precipitate",
    "odor": "Odorless", "melting_point": None, "boiling_point": None,
    "density": 3.4, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Weakly basic. Ksp = 2.79×10⁻³⁹. Dissolves in strong acids: Fe(OH)3 + 3HCl → FeCl3 + 3H2O.",
    "std_enthalpy_formation": -823.0, "std_gibbs_free_energy": -696.5,
    "std_entropy": 106.7, "lattice_energy": None,
    "ghs_hazard_codes": "None",
    "nfpa_health": 0, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": False, "is_carcinogenic": False,
    "environmental_impact": "Naturally occurring. Component of soils.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Water purification, pigment, catalyst support.",
    "industrial_production_method": "FeCl3 + 3NaOH → Fe(OH)3↓ + 3NaCl",
    "notes": "Red-brown precipitate. Confirms Fe3+ in qualitative analysis. Ksp extremely small. Component of rust (with Fe2O3·xH2O). Colloidal gold-red color (classic colloid demonstration).",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },

  # ── TRANSITION METALS: COPPER (Z=29) ────────────────────────
  {
    "formula": "CuO", "name_common": "Copper(II) oxide",
    "name_iupac": "Copper(II) oxide", "cas_number": "1317-38-0",
    "primary_element_atomic_number": 29, "primary_element_symbol": "Cu",
    "oxidation_state_of_element": 2, "compound_class": "oxide",
    "molecular_mass": 79.55, "physical_state_298k": "solid",
    "color": "black", "appearance": "Black powder",
    "odor": "Odorless", "melting_point": 1599.0, "boiling_point": None,
    "density": 6.315, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice", "electron_pair_geometry": "ionic lattice",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. CuO + H2SO4 → CuSO4 + H2O.",
    "std_enthalpy_formation": -157.3, "std_gibbs_free_energy": -129.7,
    "std_entropy": 42.6, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H400, H410",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 470.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Very toxic to aquatic organisms. Copper accumulates in environment.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Ceramics and glass coloring (blue/green), catalyst, p-type semiconductor.",
    "industrial_production_method": "2Cu + O2 → 2CuO at 300-800°C",
    "notes": "Black color due to d-d transitions in Cu2+. More stable than Cu2O at higher temperatures. Classic reduction: CuO + H2 → Cu + H2O (red copper appears). Cu2+ is d9 — Jahn-Teller distorted octahedral geometry.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Cu2O", "name_common": "Copper(I) oxide",
    "name_iupac": "Dicopper oxide", "cas_number": "1317-39-1",
    "primary_element_atomic_number": 29, "primary_element_symbol": "Cu",
    "oxidation_state_of_element": 1, "compound_class": "oxide",
    "molecular_mass": 143.09, "physical_state_298k": "solid",
    "color": "red", "appearance": "Brick-red powder or crystals (cuprite)",
    "odor": "Odorless", "melting_point": 1505.0, "boiling_point": None,
    "density": 6.0, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic lattice (cuprite structure)", "electron_pair_geometry": "linear (Cu+)",
    "hybridization": "sp (Cu+)", "bond_angle": "180°", "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": 2, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": False,
    "acid_base_notes": "Basic oxide. Cu+ disproportionates in acid: Cu2O + H2SO4 → Cu + CuSO4 + H2O. Cu+ unstable in aqueous solution.",
    "std_enthalpy_formation": -168.6, "std_gibbs_free_energy": -146.0,
    "std_entropy": 93.1, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H400, H410",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 470.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Very toxic to aquatic organisms.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Antifouling paints (ship hulls), p-type semiconductor, solar cells, ruby red glass coloring.",
    "industrial_production_method": "4Cu + O2 → 2Cu2O (limited oxygen) or reduction of CuO.",
    "notes": "Cu+ tends to disproportionate in water: 2Cu+ → Cu0 + Cu2+. Basis of Fehling's test: Cu2+ (blue) → Cu2O (red ppt) when reducing sugars present. Cuprite mineral form.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "CuSO4", "name_common": "Copper(II) sulfate",
    "name_iupac": "Copper(II) sulfate", "cas_number": "7758-98-7",
    "primary_element_atomic_number": 29, "primary_element_symbol": "Cu",
    "oxidation_state_of_element": 2, "compound_class": "salt",
    "molecular_mass": 159.61, "physical_state_298k": "solid",
    "color": "white", "appearance": "White anhydrous; blue pentahydrate CuSO4·5H2O",
    "odor": "Odorless", "melting_point": 933.0, "boiling_point": None,
    "density": 3.6, "solubility_in_water": "soluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": True, "is_base": False, "is_amphoteric": False,
    "acid_base_notes": "Acidic salt. Cu2+ hydrolyzes. pH of 0.1M ≈ 4.",
    "std_enthalpy_formation": -771.4, "std_gibbs_free_energy": -661.9,
    "std_entropy": 109.2, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H319, H400, H410",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": 481.0, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Toxic to aquatic life. Cu accumulates in sediments.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fungicide (Bordeaux mixture), electroplating, swimming pool algaecide, analytical chemistry.",
    "industrial_production_method": "Cu + 2H2SO4(conc) → CuSO4 + SO2 + 2H2O",
    "notes": "Blue vitriol (CuSO4·5H2O). Anhydrous = white; hydrated = blue ([Cu(H2O)4]2+ gives blue color by d-d transition). Turns white on heating. Classic electrolysis experiment. Component of Fehling's solution.",
    "data_source": "NIST WebBook, CRC Handbook 97th Ed",
  },
  {
    "formula": "Cu(OH)2", "name_common": "Copper(II) hydroxide",
    "name_iupac": "Copper(II) hydroxide", "cas_number": "20427-59-2",
    "primary_element_atomic_number": 29, "primary_element_symbol": "Cu",
    "oxidation_state_of_element": 2, "compound_class": "hydroxide",
    "molecular_mass": 97.56, "physical_state_298k": "solid",
    "color": "blue", "appearance": "Blue gelatinous precipitate",
    "odor": "Odorless", "melting_point": None, "boiling_point": None,
    "density": 3.37, "solubility_in_water": "insoluble",
    "molecular_geometry": "ionic", "electron_pair_geometry": "ionic",
    "hybridization": "ionic", "bond_angle": None, "vsepr_notation": None,
    "is_polar": None, "dipole_moment": None,
    "coordination_number": None, "ligands": None,
    "is_acid": False, "is_base": True, "is_amphoteric": True,
    "acid_base_notes": "Weakly amphoteric. As base: Cu(OH)2 + H2SO4 → CuSO4 + 2H2O. Dissolves in excess NaOH: Cu(OH)2 + 2NaOH → Na2[Cu(OH)4]. Ksp = 2.19×10⁻¹⁹.",
    "std_enthalpy_formation": -449.8, "std_gibbs_free_energy": -372.0,
    "std_entropy": 108.0, "lattice_energy": None,
    "ghs_hazard_codes": "H302, H400, H410",
    "nfpa_health": 2, "nfpa_flammability": 0, "nfpa_reactivity": 0,
    "ld50_mg_kg": None, "is_toxic": True, "is_carcinogenic": False,
    "environmental_impact": "Very toxic to aquatic organisms.",
    "biodegradable": False, "ozone_depleting": False, "greenhouse_gas": False,
    "discovery_year": None,
    "uses": "Fungicide, prec